# @package _global_

model:
  _target_: starter_kit.baselines.mlp.MLPModel
  n_epochs: ${n_epochs}
  learning_rate: ${learning_rate}
  weight_decay: 0.
  best_threshold: 0.99
  log_csv: true

network:
  _target_: starter_kit.baselines.mlp.MLPNetwork
  input_dim: 30
  hidden_dim: 256
  n_layers: 4
