# @package _global_

model:
  _target_: starter_kit.baselines.parametric.ParametricModel
  n_epochs: ${n_epochs}
  learning_rate: ${learning_rate}
  weight_decay: 0.
  best_threshold: 0.99
  log_csv: true

network:
  _target_: starter_kit.baselines.sundquist.SundquistNetwork
