# @package _global_

defaults:
  - /test_data: test_era5_region1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      test_data: test_era5_region1,test_era5_region2,test_aimip_region1,test_aimip_region2
